// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/accounting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accounting">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/accounting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/dashboard/[role]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/[role]">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/dashboard/[role]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/expenses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/expenses">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/expenses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/fep/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fep">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/fep/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/inventory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/inventory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/lots/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lots/new">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/lots/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/lots/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lots">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/lots/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/partners/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partners">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/partners/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/purchases/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchases">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/purchases/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/reports/balance-sheet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/balance-sheet">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/reports/balance-sheet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/reports/cash-flow/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/cash-flow">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/reports/cash-flow/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/reports/general-ledger/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/general-ledger">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/reports/general-ledger/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/reports/profit-loss/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/profit-loss">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/reports/profit-loss/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/reports/trial-balance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/trial-balance">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/reports/trial-balance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/sales/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/new">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/sales/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/sales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/sales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/settings/security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/security">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/settings/security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/users">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/users/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/users/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/users/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/login/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/login/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/signup/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/signup/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
